# main menu navigation
menu:
  Home: /
  # About: /about
  # Archive: /archives

widgets:
  - recent_posts
  - category
  - profile
  # - tag
  # - archive
  # - friend_links

# social config
social:
  zhihu: /
  twitter: /
  facebook: /
  linkedin: /
  instagram: /
  github: /

user:
  name:
  avatar: /images/avatar.jpg
  location: this plant
  description: time is passing.
  footnotes: # footnotes

# documents: https://github.com/utterance/utterances
# API config: https://utteranc.es/
comment_utteranc:
  enable: false
  repo: Haojen/Claudia-theme-blog # your blog repo


# documents: https://valine.js.org/quickstart.html
comment_valine:
  enable: false
  appId:
  appKey:

comment_disqus:
    enable: false
    url:  # the url of your website main domain like this https://xxx.xxx/
    name: # the short name in disqus

# dark
# light
# user-can-set
appearance: auto # Default value is auto

# Miscellaneous
favicon: /favicon.png

friend_links:
  - title: Google
    link: https://www.google.com/
  - title: Github
    link: https://www.github.com/
  - title: V2EX
    link: https://v2ex.com/
  - title: Twitter
    link: https://twitter.com/

# Google Analytics
ga_track_id:
ga_domain:

# Baidu Analytics
ba_track_id:

# Matomo Analytics
matomo_tracker_domain:

# picture of about page
about_pic: /images/about.png

image_zoom:
  enable: true